version: '3.8'

services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    build: ./database
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
