version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      STAGE: motd
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://motd:motd@db/motd
    networks:
      - default
    ports:
      - 5000:5000

  db:
    environment:
      POSTGRES_USER: motd
      POSTGRES_PASSWORD: motd
      POSTGRES_DB: motd
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
